# Update project_id with your Supabase project reference (e.g. "abcd1234").
project_id = "xvietalzobghdwhzmbto"

# Optionally point the CLI to a dotenv file that contains secrets.
# dotenv_path = "../.env"

[functions]
# Add patterns here if certain files should be ignored when deploying functions.
[functions.ignore]
