name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  quality:
    name: Type, lint, and test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Run TypeScript checks
        run: npm run typecheck

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test -- --runInBand
